# Pytorch Tensor #

In [1]:
import torch
import numpy as np
import math

In [2]:
#Defining a tensor from data
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [3]:
#Creating tensor from NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


** A new tensor retains the properties(shape, datatype) of the argument tensor, unless explicitly overidden. **

In [4]:
x_ones = torch.ones_like(x_data) #Retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

x_rand = torch.rand_like(x_data, dtype=float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.4464, 0.7805],
        [0.5131, 0.3480]]) 

Random Tensor: 
 tensor([[0.8112, 0.8429],
        [0.3899, 0.6672]], dtype=torch.float64) 



In [5]:
# "shape" is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

shape1 = (2,3)
shape2 = (2,3,4)
rand_tensor = torch.rand(shape1)
ones_tensor = torch.ones(shape1)
zeros_tensor = torch.zeros(shape2)



print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.3826, 0.8755, 0.4226],
        [0.0113, 0.2760, 0.1474]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


**Printing attributes of tensor**

In [6]:
tensor = torch.rand(3,4)

print(tensor.shape) #Dimension
print(tensor.dtype) #Data Type
print(tensor.device) #Device for Storage

torch.Size([3, 4])
torch.float32
cpu


**Over 1200 tnsor operations exist, including arithmetic, linear algebra, matrix manipulation(transposing, indexing, slicing), sampling and more**

**Tensors typically created on the CPU, but often explicitly move to accelerator using .to method**

In [7]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [8]:
#Standard numpy-liek indexing and slicing:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[..., -1]}")
tensor [:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
#Joining tensors or Concatenate(linking together in a chain or series) tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
#Arithmetic operations
#tensor.T returns the transpose of a tensor

# Compute matrix multiplication between two tensors
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

#This computes the element-wise product
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor, out=z3)
#Note that, the z3 is printed because Jupyter automatically prints the last line


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])